does not compile:
Error:(36, 24) value map is not a member of Boolean
Error occurred in an application involving default arguments.
  val w: String = write(v)
Error:(36, 24) missing argument list for method apply in object Tuple1
Unapplied methods are only converted to functions when a function type is expected.
You can make this conversion explicit by writing `apply _` or `apply(_)` instead of `apply`.
Error occurred in an application involving default arguments.
  val w: String = write(v)
Error:(36, 24) ambiguous implicit values:
 both value derive$macro$8 of type => upickle.default.Writer[app.TestuPickle.Test[Int]]
 and value IntRW in trait Implicits of type => upickle.default.Aliases.RW[Int]
 match expected type upickle.default.Writer[T1]
Error occurred in an application involving default arguments.
  val w: String = write(v)
Error:(36, 24) diverging implicit expansion for type upickle.default.Writer[T1]
starting with macro method macroW in trait LowPriX
Error occurred in an application involving default arguments.
  val w: String = write(v)
Error:(36, 24) not enough arguments for method Tuple1W: (implicit evidence$1: upickle.default.Writer[T1])upickle.default.Writer[(T1,)].
Unspecified value parameter evidence$1.
Error occurred in an application involving default arguments.
  val w: String = write(v)